//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrnekDBEntities : DbContext
    {
        public OrnekDBEntities()
            : base("name=OrnekDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Proc_Kategoriler_Islem_Result> Proc_Kategoriler_Islem(string islem, Nullable<int> kategoriID, Nullable<int> ustKategoriID, string kategoriBaslik, string kategoriAciklama, string kategoriResimUrl)
        {
            var islemParameter = islem != null ?
                new ObjectParameter("Islem", islem) :
                new ObjectParameter("Islem", typeof(string));
    
            var kategoriIDParameter = kategoriID.HasValue ?
                new ObjectParameter("KategoriID", kategoriID) :
                new ObjectParameter("KategoriID", typeof(int));
    
            var ustKategoriIDParameter = ustKategoriID.HasValue ?
                new ObjectParameter("UstKategoriID", ustKategoriID) :
                new ObjectParameter("UstKategoriID", typeof(int));
    
            var kategoriBaslikParameter = kategoriBaslik != null ?
                new ObjectParameter("KategoriBaslik", kategoriBaslik) :
                new ObjectParameter("KategoriBaslik", typeof(string));
    
            var kategoriAciklamaParameter = kategoriAciklama != null ?
                new ObjectParameter("KategoriAciklama", kategoriAciklama) :
                new ObjectParameter("KategoriAciklama", typeof(string));
    
            var kategoriResimUrlParameter = kategoriResimUrl != null ?
                new ObjectParameter("KategoriResimUrl", kategoriResimUrl) :
                new ObjectParameter("KategoriResimUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Kategoriler_Islem_Result>("Proc_Kategoriler_Islem", islemParameter, kategoriIDParameter, ustKategoriIDParameter, kategoriBaslikParameter, kategoriAciklamaParameter, kategoriResimUrlParameter);
        }
    
        public virtual ObjectResult<Proc_Markalar_Islem_Result> Proc_Markalar_Islem(string islem, Nullable<int> markaID, string markaBaslik, string markaAciklama, string markaResimUrl)
        {
            var islemParameter = islem != null ?
                new ObjectParameter("Islem", islem) :
                new ObjectParameter("Islem", typeof(string));
    
            var markaIDParameter = markaID.HasValue ?
                new ObjectParameter("markaID", markaID) :
                new ObjectParameter("markaID", typeof(int));
    
            var markaBaslikParameter = markaBaslik != null ?
                new ObjectParameter("markaBaslik", markaBaslik) :
                new ObjectParameter("markaBaslik", typeof(string));
    
            var markaAciklamaParameter = markaAciklama != null ?
                new ObjectParameter("markaAciklama", markaAciklama) :
                new ObjectParameter("markaAciklama", typeof(string));
    
            var markaResimUrlParameter = markaResimUrl != null ?
                new ObjectParameter("markaResimUrl", markaResimUrl) :
                new ObjectParameter("markaResimUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Markalar_Islem_Result>("Proc_Markalar_Islem", islemParameter, markaIDParameter, markaBaslikParameter, markaAciklamaParameter, markaResimUrlParameter);
        }
    
        public virtual ObjectResult<Proc_Urunler_Islem_Result> Proc_Urunler_Islem(string islem, Nullable<int> urunID, Nullable<int> kategoriID, string urunKodu, string urunBaslik, string urunAciklama, string urunResimUrl)
        {
            var islemParameter = islem != null ?
                new ObjectParameter("Islem", islem) :
                new ObjectParameter("Islem", typeof(string));
    
            var urunIDParameter = urunID.HasValue ?
                new ObjectParameter("UrunID", urunID) :
                new ObjectParameter("UrunID", typeof(int));
    
            var kategoriIDParameter = kategoriID.HasValue ?
                new ObjectParameter("KategoriID", kategoriID) :
                new ObjectParameter("KategoriID", typeof(int));
    
            var urunKoduParameter = urunKodu != null ?
                new ObjectParameter("UrunKodu", urunKodu) :
                new ObjectParameter("UrunKodu", typeof(string));
    
            var urunBaslikParameter = urunBaslik != null ?
                new ObjectParameter("UrunBaslik", urunBaslik) :
                new ObjectParameter("UrunBaslik", typeof(string));
    
            var urunAciklamaParameter = urunAciklama != null ?
                new ObjectParameter("UrunAciklama", urunAciklama) :
                new ObjectParameter("UrunAciklama", typeof(string));
    
            var urunResimUrlParameter = urunResimUrl != null ?
                new ObjectParameter("UrunResimUrl", urunResimUrl) :
                new ObjectParameter("UrunResimUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Urunler_Islem_Result>("Proc_Urunler_Islem", islemParameter, urunIDParameter, kategoriIDParameter, urunKoduParameter, urunBaslikParameter, urunAciklamaParameter, urunResimUrlParameter);
        }
    }
}
